{"name": "test_fail_authorisation_with_non_existent_user", "status": "passed", "description": "Нельзя авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "start": 1720263256677, "stop": 1720263256784, "uuid": "fbc8b191-01b7-47cb-b48e-96fa24f7f6b7", "historyId": "01313fb35f7e24a63861807d540ffaf5", "testCaseId": "01313fb35f7e24a63861807d540ffaf5", "fullName": "tests.test_courier.TestCourierLogin#test_fail_authorisation_with_non_existent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-MJ06UFI"}, {"name": "thread", "value": "20160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}